trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

variables:
- group: myexample-iac-terraform-dev

stages:
- stage: Build
  displayName: 'Build terraform code'
  jobs:
    - job: BuildJob
      steps: 
        - task: CopyFiles@2
          displayName: 'Copy all repository contents to artifacts'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)' # This targets the root of your repository
            Contents: '**' # Copies absolutely everything inside the root
            TargetFolder: '$(Build.ArtifactStagingDirectory)' # Fixed path to ensure it matches the publish task!

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Terraform Artifacts'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'terraform_drop'

- stage: Deploy
  displayName: 'Deploy Terraform Setup'
  dependsOn: Build
  jobs:
    - job: Bootstrap
      displayName: 'Bootstrap Azure Resources'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: AzureCLI@2
          displayName: 'Ensure Backend Storage Exists'
          inputs:
            azureSubscription: 'MyExample-Azure'
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              az group create --location eastus --name myexample-tf-rg
              az storage account create --name myexamplestorage --resource-group myexample-tf-rg --location westus2 --sku Standard_ZRS --encryption-services blob
              az storage container create --account-name myexamplestorage --name myexamplestorage

    - deployment: Terraform_Deploy
      displayName: 'Terraform Deploy'
      dependsOn: Bootstrap
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: terraform_drop

              - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
                displayName: 'Install Terraform'
                inputs:
                  terraformVersion: '1.6.6'
                  
              - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
                displayName: 'Terraform : init'
                inputs:
                  command: init
                  provider: 'azurerm'
                  workingDirectory: '$(Pipeline.Workspace)/terraform_drop/Environments/dev'
                  backendServiceArm: '$(AzureServiceConnectionName)'
                  backendAzureRmResourceGroupName: '$(tf_resource_group_name)'
                  backendAzureRmStorageAccountName: '$(tf_storage_name)'
                  backendAzureRmContainerName: '$(tf_storage_container_name)'
                  backendAzureRmKey: '$(tf_storage_key)'

              - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
                displayName: 'Terraform : plan'
                inputs:
                  command: plan
                  provider: 'azurerm'
                  workingDirectory: '$(Pipeline.Workspace)/terraform_drop/Environments/dev'
                  environmentServiceNameAzureRM: '$(AzureServiceConnectionName)'
                  commandOptions: '-var-file=terraform.tfvars -out=tfplan'

              - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
                displayName: 'Terraform : apply -auto-approve'
                inputs:
                  command: apply
                  provider: 'azurerm'
                  workingDirectory: '$(Pipeline.Workspace)/terraform_drop/Environments/dev'
                  commandOptions: 'tfplan'
                  environmentServiceNameAzureRM: '$(AzureServiceConnectionName)'
