trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: myexample-iac-terraform-dev

stages:
- stage: Build
  displayName: 'Build terraform code'
  jobs:
    - job: BuildJob
      steps:  

        - task: CopyFiles@2
          displayName: 'Copy all repository contents to artifacts'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)' # This targets the root of your repository
            Contents: '**' # Copies absolutely everything inside the root
            TargetFolder: '$(Build.ArtifactStagingDirectory)' # Fixed path to ensure it matches the publish task!

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Terraform Artifacts'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'terraform_drop'


